### ISSUE TITLE
`gopass edit` is broken

### ISSUE THREAD

**Issue by adius** [justwatchcom/gopass#122]
Seems like commit 428e504745138f3cd3cc166f58bb14b54926b86c broke it.
It just freezes and doesn't do anything.
After creating an empty `.pass-template` file it worked again as expected.

Also part of the problem: There does not seem to be a (regression) test for `gopass edit`  ...

**Comment by dominikschulz** [comment]
Which version of gopass are you using?

We notied this bug as well and it should be fixed in the latest release (1.1.0).

**Comment by adius** [comment]
```sh
$ gopass version
gopass HEAD (n/a ) go1.8.3
```

Haha, this is not particularly helpful. 

`gopass version` should print the output of `git describe` which is much more helpful
In my case that's `v1.1.0-rc2-6-gd4bb126`

**Comment by dominikschulz** [comment]
Our releases include full version information like this: `gopass 1.1.0 (4857b8a1 2017-05-31 13:27:57) go1.8`

If you build it yourself using `go build` there is no version information injected. If you want to suggest a way to improve that feel free to open an PR.

Your bug should be already fixed in `1.1.0 final`. Feel free to re-open if you still have problems.

**Comment by adius** [comment]
> If you want to suggest a way to improve that feel free to open an PR

Well, I guess someone who build it from source knows how to get the version even if `gopass version` doesn't print it. => Good enough for the time being =P
I'll better just switch to the brew installation...

> Your bug should be already fixed in 1.1.0 final

Mh, I upgraded to `gopass 1.1.0 (4857b8a1 2017-06-09 07:24:10) go1.8.3` but I'm still having this issue...

> Feel free to re-open if you still have problems

I can't reopen it ...
